export const ActionTypes = {
 
  SET_MRF_DATA: 'SET_MRF_DATA',
  SUBMIT_MRF_FORM: 'SUBMIT_MRF_FORM',
 
  SET_USER_PROFILE: 'SET_USER_PROFILE',
  UPDATE_USER_PROFILE: 'UPDATE_USER_PROFILE',
 
  ADD_USER: 'ADD_USER',
  SET_USERS: 'SET_USERS',
  SET_APPICATION_TITLE: 'SET_APPICATION_TITLE',
  SET_APPLICATION_TITLE: "SET_APPLICATION_TITLE",
  ADD_ADMIN_ROLE: "ADD_ADMIN_ROLE",
  SET_ADMIN_ROLES: "SET_ADMIN_ROLES",
  LOGIN_START: "LOGIN_START",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  SET_SUCCESS_MESSAGE: "SET_SUCCESS_MESSAGE",
  RESET_LOGIN_MESSAGES: "RESET_LOGIN_MESSAGES",
  SET_EMPLOYEES: "SET_EMPLOYEES",
  SET_LOCATIONS: "SET_LOCATIONS",
  SET_DEPARTMENTS: "SET_DEPARTMENTS",
  SET_JOB_TITLES: "SET_JOB_TITLES",
  SET_MANAGING_AUTHORITIES: "SET_MANAGING_AUTHORITIES",
  ADD_EMPLOYEE: "ADD_EMPLOYEE",
  SET_EMAIL: "SET_EMAIL",
  ADD_CLIENT_REQUIREMENTS: "ADD_CLIENT_REQUIREMENTS",
  SET_ADMIN_DEPARTMENTS: 'SET_ADMIN_DEPARTMENTS',
  ADD_ADMIN_DEPARTMENT: 'ADD_ADMIN_DEPARTMENT',
  SET_BUSSINESS_UNITS: "SET_BUSINESS_UNITS",
  ADD_BUSSINESS_UNIT: "ADD_BUSINESS_UNIT",
  SET_ADMIN_LOCATIONS: 'SET_ADMIN_LOCATIONS',
  ADD_ADMIN_LOCATION: 'ADD_ADMIN_LOCATION',
  ADD_LOCATION_REQUEST: 'ADD_LOCATION_REQUEST',
  ADD_LOCATION_SUCCESS: 'ADD_LOCATION_SUCCESS',
  ADD_LOCATION_FAILURE: 'ADD_LOCATION_FAILURE',
  
  ADD_TASK: "ADD_TASK",
  DELETE_TASK: "DELETE_TASK",
  UPDATE_TASK_STATUS: "UPDATE_TASK_STATUS",
 
  UPDATE_ADMIN_LOCATION: 'UPDATE_ADMIN_LOCATION',
  UPDATE_LOCATION_REQUEST: 'UPDATE_LOCATION_REQUEST',
  UPDATE_LOCATION_SUCCESS: 'UPDATE_LOCATION_SUCCESS',
  UPDATE_LOCATION_FAILURE: 'UPDATE_LOCATION_FAILURE',
 
 
 
};
 